#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

for dir in "d"/*; do

#dir="d/acl"
file="${dir/d\//}"
echo $file
cd $dir
npm install
cd ../..
cp tsconfig.template.json "$dir/tsconfig.json"
node_modules/.bin/tsickle --typed --externs="externs/$file.extern.js" -- --project "$dir" || echo ">>
fuck $dir"
rm -rf "$dir/node_modules"

done
