version: 2
jobs:
  build:
    working_directory: ~/w
    docker:
      - image: honzabrecka/cljnode:0.1.0
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: lein uberjar
      - run: java -jar target/uberjar/generator-0.1.0-SNAPSHOT-standalone.jar @types/react
      - run: cat externs/react.extern.js
