/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/boolify-string/index.d.ts:

/**
 * @param {?} obj
 * @return {boolean}
 */
function boolifyString(obj) {}

/* TODO: ExportAssignment in  */
