/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/bootstrap-datepicker/index.d.ts:
/**
 * @record
 * @struct
 */
function DatepickerOptions() {}
 /** @type {(string|!DatepickerCustomFormatOptions)} */
DatepickerOptions.prototype.format;
 /** @type {number} */
DatepickerOptions.prototype.weekStart;
 /** @type {(string|!Date)} */
DatepickerOptions.prototype.startDate;
 /** @type {(string|!Date)} */
DatepickerOptions.prototype.endDate;
 /** @type {boolean} */
DatepickerOptions.prototype.autoclose;
 /** @type {number} */
DatepickerOptions.prototype.startView;
 /** @type {(boolean|string)} */
DatepickerOptions.prototype.todayBtn;
 /** @type {boolean} */
DatepickerOptions.prototype.todayHighlight;
 /** @type {boolean} */
DatepickerOptions.prototype.keyboardNavigation;
 /** @type {string} */
DatepickerOptions.prototype.language;
 /** @type {function(!Date): (string|boolean|!DatepickerBeforeShowDayResponse)} */
DatepickerOptions.prototype.beforeShowDay;
 /** @type {function(!Date): (string|boolean|!DatepickerBeforeShowResponse)} */
DatepickerOptions.prototype.beforeShowYear;
 /** @type {function(!Date): (string|boolean|!DatepickerBeforeShowResponse)} */
DatepickerOptions.prototype.beforeShowDecade;
 /** @type {function(!Date): (string|boolean|!DatepickerBeforeShowResponse)} */
DatepickerOptions.prototype.beforeShowCentury;
 /** @type {boolean} */
DatepickerOptions.prototype.calendarWeeks;
 /** @type {boolean} */
DatepickerOptions.prototype.clearBtn;
 /** @type {!Array<number>} */
DatepickerOptions.prototype.daysOfWeekDisabled;
 /** @type {boolean} */
DatepickerOptions.prototype.forceParse;
 /** @type {!Array<?>} */
DatepickerOptions.prototype.inputs;
 /** @type {(number|string)} */
DatepickerOptions.prototype.minViewMode;
 /** @type {(number|string)} */
DatepickerOptions.prototype.maxViewMode;
 /** @type {(number|boolean)} */
DatepickerOptions.prototype.multidate;
 /** @type {string} */
DatepickerOptions.prototype.multidateSeparator;
 /** @type {string} */
DatepickerOptions.prototype.orientation;
 /** @type {(number|boolean)} */
DatepickerOptions.prototype.assumeNearbyYear;
 /** @type {string} */
DatepickerOptions.prototype.viewMode;
 /** @type {?} */
DatepickerOptions.prototype.templates;
 /** @type {number} */
DatepickerOptions.prototype.zIndexOffset;
 /** @type {boolean} */
DatepickerOptions.prototype.showOnFocus;
 /** @type {boolean} */
DatepickerOptions.prototype.immediateUpdates;
 /** @type {string} */
DatepickerOptions.prototype.title;
 /** @type {string} */
DatepickerOptions.prototype.container;
 /** @type {(string|!Array<string>)} */
DatepickerOptions.prototype.datesDisabled;
 /** @type {(string|!Array<number>)} */
DatepickerOptions.prototype.daysOfWeekHighlighted;
 /** @type {(string|!Date|!DatepickerViewDate)} */
DatepickerOptions.prototype.defaultViewDate;
 /** @type {boolean} */
DatepickerOptions.prototype.updateViewDate;
/**
 * @record
 * @struct
 */
function DatepickerViewDate() {}
 /** @type {number} */
DatepickerViewDate.prototype.year;
 /** @type {number} */
DatepickerViewDate.prototype.month;
 /** @type {number} */
DatepickerViewDate.prototype.day;
/**
 * @record
 * @struct
 */
function DatepickerBeforeShowResponse() {}
 /** @type {boolean} */
DatepickerBeforeShowResponse.prototype.enabled;
 /** @type {string} */
DatepickerBeforeShowResponse.prototype.classes;
 /** @type {string} */
DatepickerBeforeShowResponse.prototype.tooltip;
/**
 * @extends {DatepickerBeforeShowResponse}
 * @record
 * @struct
 */
function DatepickerBeforeShowDayResponse() {}
 /** @type {string} */
DatepickerBeforeShowDayResponse.prototype.content;
/**
 * @record
 * @struct
 */
function DatepickerCustomFormatOptions() {}

/**
 * @param {string} date
 * @param {?} format
 * @param {?} language
 * @return {string}
 */
DatepickerCustomFormatOptions.prototype.toDisplay = function(date, format, language) {};

/**
 * @param {string} date
 * @param {?} format
 * @param {?} language
 * @return {!Date}
 */
DatepickerCustomFormatOptions.prototype.toValue = function(date, format, language) {};
/**
 * @extends {JQueryEventObject}
 * @record
 * @struct
 */
function DatepickerEventObject() {}
 /** @type {!Date} */
DatepickerEventObject.prototype.date;
 /** @type {!Array<!Date>} */
DatepickerEventObject.prototype.dates;

/**
 * @param {number|string=} ix_or_format
 * @param {string=} format
 * @return {string}
 */
DatepickerEventObject.prototype.format = function(ix_or_format, format) {};

/**
 * @param {string|!DatepickerOptions=} methodName_or_options
 * @param {?=} params
 * @return {?<!HTMLElement>|?}
 */
JQuery.prototype.datepicker = function(methodName_or_options, params) {};

/**
 * @param {string} events
 * @param {string|function(!DatepickerEventObject): ?=} selector_or_handler
 * @param {function(!DatepickerEventObject): ?=} handler
 * @return {?<!HTMLElement>}
 */
JQuery.prototype.off = function(events, selector_or_handler, handler) {};

/**
 * @param {string} events
 * @param {string|function(!DatepickerEventObject): ?} selector_or_handler
 * @param {?|function(!DatepickerEventObject): ?=} data_or_handler
 * @param {function(!DatepickerEventObject): ?=} handler
 * @return {?<!HTMLElement>}
 */
JQuery.prototype.on = function(events, selector_or_handler, data_or_handler, handler) {};
