/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/canvas-gauges/index.d.ts:
/** @const */
var CanvasGauges = {};

/** @typedef {string} */
CanvasGauges.FontStyle;

/** @typedef {string} */
CanvasGauges.FontWeight;

/** @typedef {(string|!HTMLElement)} */
CanvasGauges.RenderTarget;
/**
 * @record
 * @struct
 */
CanvasGauges.AnimationRule = function() {};

/* TODO: CallSignature: CanvasGauges */
/**
 * @record
 * @struct
 */
CanvasGauges.Highlight = function() {};
 /** @type {number} */
CanvasGauges.Highlight.prototype.from;
 /** @type {number} */
CanvasGauges.Highlight.prototype.to;
 /** @type {string} */
CanvasGauges.Highlight.prototype.color;
/**
 * @record
 * @struct
 */
CanvasGauges.EventListeners = function() {};

/* TODO: IndexSignature: CanvasGauges */

/** @typedef {(!Array<string>|!Array<number>)} */
CanvasGauges.MajorTicks;
/**
 * @record
 * @struct
 */
CanvasGauges.GenericOptions = function() {};
 /** @type {(string|!HTMLElement)} */
CanvasGauges.GenericOptions.prototype.renderTo;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.width;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.height;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.minValue;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.maxValue;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.value;
 /** @type {(string|boolean)} */
CanvasGauges.GenericOptions.prototype.units;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.exactTicks;
 /** @type {(!Array<string>|!Array<number>)} */
CanvasGauges.GenericOptions.prototype.majorTicks;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.minorTicks;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.strokeTicks;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.animatedValue;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.animateOnInit;
 /** @type {(string|boolean)} */
CanvasGauges.GenericOptions.prototype.title;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.borders;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.numbersMargin;
 /** @type {!CanvasGauges.EventListeners} */
CanvasGauges.GenericOptions.prototype.listeners;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.valueInt;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.valueDec;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.majorTicksInt;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.majorTicksDec;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.animation;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.animationDuration;
 /** @type {(string|!CanvasGauges.AnimationRule)} */
CanvasGauges.GenericOptions.prototype.animationRule;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorPlate;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorPlateEnd;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorMajorTicks;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorMinorTicks;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorTitle;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorUnits;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorNumbers;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorNeedle;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorNeedleEnd;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorValueText;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorValueTextShadow;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBorderShadow;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBorderOuter;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBorderOuterEnd;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBorderMiddle;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBorderMiddleEnd;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBorderInner;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBorderInnerEnd;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorValueBoxRect;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorValueBoxRectEnd;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorValueBoxBackground;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorValueBoxShadow;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorNeedleShadowUp;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorNeedleShadowDown;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBarStroke;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBar;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBarProgress;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.colorBarShadow;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontNumbers;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontTitle;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontUnits;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontValue;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.fontTitleSize;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.fontValueSize;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.fontUnitsSize;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.fontNumbersSize;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontTitleStyle;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontValueStyle;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontUnitsStyle;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontNumbersStyle;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontTitleWeight;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontValueWeight;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontUnitsWeight;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.fontNumbersWeight;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.needle;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.needleShadow;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.needleType;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.needleStart;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.needleEnd;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.needleWidth;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.borderOuterWidth;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.borderMiddleWidth;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.borderInnerWidth;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.borderShadowWidth;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.valueBox;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.valueBoxWidth;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.valueBoxStroke;
 /** @type {string} */
CanvasGauges.GenericOptions.prototype.valueText;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.valueTextShadow;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.valueBoxBorderRadius;
 /** @type {!Array<!CanvasGauges.Highlight>} */
CanvasGauges.GenericOptions.prototype.highlights;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.highlightsWidth;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.barWidth;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.barStrokeWidth;
 /** @type {boolean} */
CanvasGauges.GenericOptions.prototype.barProgress;
 /** @type {number} */
CanvasGauges.GenericOptions.prototype.barShadow;
/**
 * @extends {CanvasGauges.GenericOptions}
 * @record
 * @struct
 */
CanvasGauges.RadialGaugeOptions = function() {};
 /** @type {number} */
CanvasGauges.RadialGaugeOptions.prototype.ticksAngle;
 /** @type {number} */
CanvasGauges.RadialGaugeOptions.prototype.startAngle;
 /** @type {string} */
CanvasGauges.RadialGaugeOptions.prototype.colorNeedleCircleOuter;
 /** @type {string} */
CanvasGauges.RadialGaugeOptions.prototype.colorNeedleCircleOuterEnd;
 /** @type {string} */
CanvasGauges.RadialGaugeOptions.prototype.colorNeedleCircleInner;
 /** @type {string} */
CanvasGauges.RadialGaugeOptions.prototype.colorNeedleCircleInnerEnd;
 /** @type {number} */
CanvasGauges.RadialGaugeOptions.prototype.needleCircleSize;
 /** @type {boolean} */
CanvasGauges.RadialGaugeOptions.prototype.needleCircleInner;
 /** @type {boolean} */
CanvasGauges.RadialGaugeOptions.prototype.needleCircleOuter;
 /** @type {string} */
CanvasGauges.RadialGaugeOptions.prototype.animationTarget;
 /** @type {boolean} */
CanvasGauges.RadialGaugeOptions.prototype.useMinPath;
/**
 * @extends {CanvasGauges.GenericOptions}
 * @record
 * @struct
 */
CanvasGauges.LinearGaugeOptions = function() {};
 /** @type {number} */
CanvasGauges.LinearGaugeOptions.prototype.borderRadius;
 /** @type {number} */
CanvasGauges.LinearGaugeOptions.prototype.barBeginCircle;
 /** @type {string} */
CanvasGauges.LinearGaugeOptions.prototype.colorBarEnd;
 /** @type {string} */
CanvasGauges.LinearGaugeOptions.prototype.colorBarProgressEnd;
 /** @type {string} */
CanvasGauges.LinearGaugeOptions.prototype.tickSide;
 /** @type {string} */
CanvasGauges.LinearGaugeOptions.prototype.needleSide;
 /** @type {string} */
CanvasGauges.LinearGaugeOptions.prototype.numberSide;
 /** @type {number} */
CanvasGauges.LinearGaugeOptions.prototype.ticksWidth;
 /** @type {number} */
CanvasGauges.LinearGaugeOptions.prototype.ticksWidthMinor;
 /** @type {number} */
CanvasGauges.LinearGaugeOptions.prototype.ticksPadding;
 /** @type {number} */
CanvasGauges.LinearGaugeOptions.prototype.barLength;
/**
 * @record
 * @struct
 */
CanvasGauges.DrawEventCallback = function() {};

/* TODO: CallSignature: CanvasGauges */
/**
 * @record
 * @struct
 */
CanvasGauges.EndEventCallback = function() {};

/* TODO: CallSignature: CanvasGauges */
/**
 * @record
 * @struct
 */
CanvasGauges.rules = function() {};
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.linear;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.quad;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.dequad;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.quint;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.dequint;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.cycle;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.decycle;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.bounce;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.debounce;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.elastic;
 /** @type {!CanvasGauges.AnimationRule} */
CanvasGauges.rules.prototype.delastic;

/**
 * @constructor
 * @struct
 * @param {(string|!CanvasGauges.AnimationRule)=} rule
 * @param {number=} duration
 * @param {!CanvasGauges.DrawEventCallback=} draw
 * @param {!CanvasGauges.EndEventCallback=} end
 */
CanvasGauges.Animation = function(rule, duration, draw, end) {};
 /** @type {number} */
CanvasGauges.Animation.prototype.duration;
 /** @type {(string|!CanvasGauges.AnimationRule)} */
CanvasGauges.Animation.prototype.rule;
 /** @type {!CanvasGauges.DrawEventCallback} */
CanvasGauges.Animation.prototype.draw;
 /** @type {!CanvasGauges.EndEventCallback} */
CanvasGauges.Animation.prototype.end;
 /** @type {!CanvasGauges.rules} */
CanvasGauges.Animation.rules;

/**
 * @param {!CanvasGauges.DrawEventCallback=} draw
 * @param {!CanvasGauges.EndEventCallback=} end
 * @return {?}
 */
CanvasGauges.Animation.prototype.animate = function(draw, end) {};

/**
 * @return {?}
 */
CanvasGauges.Animation.prototype.destroy = function() {};

/**
 * @constructor
 * @struct
 * @param {!HTMLCanvasElement} element
 * @param {number=} width
 * @param {number=} height
 */
CanvasGauges.SmartCanvas = function(element, width, height) {};
 /** @type {!HTMLCanvasElement} */
CanvasGauges.SmartCanvas.prototype.element;
 /** @type {!HTMLCanvasElement} */
CanvasGauges.SmartCanvas.prototype.elementClone;
 /** @type {!CanvasRenderingContext2D} */
CanvasGauges.SmartCanvas.prototype.context;
 /** @type {!CanvasRenderingContext2D} */
CanvasGauges.SmartCanvas.prototype.contextClone;
 /** @type {number} */
CanvasGauges.SmartCanvas.prototype.drawWidth;
 /** @type {number} */
CanvasGauges.SmartCanvas.prototype.drawHeight;
 /** @type {number} */
CanvasGauges.SmartCanvas.prototype.drawX;
 /** @type {number} */
CanvasGauges.SmartCanvas.prototype.drawY;
 /** @type {number} */
CanvasGauges.SmartCanvas.prototype.minSide;
 /** @type {number} */
CanvasGauges.SmartCanvas.prototype.width;
 /** @type {number} */
CanvasGauges.SmartCanvas.prototype.height;
 /** @type {number} */
CanvasGauges.SmartCanvas.prototype.pixelRatio;
 /** @type {!Array<!CanvasGauges.SmartCanvas>} */
CanvasGauges.SmartCanvas.collection;

/**
 * @return {?}
 */
CanvasGauges.SmartCanvas.prototype.init = function() {};

/**
 * @return {?}
 */
CanvasGauges.SmartCanvas.prototype.onRedraw = function() {};

/**
 * @return {?}
 */
CanvasGauges.SmartCanvas.prototype.destroy = function() {};

/**
 * @return {!CanvasGauges.SmartCanvas}
 */
CanvasGauges.SmartCanvas.prototype.commit = function() {};

/**
 * @return {!CanvasGauges.SmartCanvas}
 */
CanvasGauges.SmartCanvas.prototype.redraw = function() {};

/**
 * @return {?}
 */
CanvasGauges.SmartCanvas.redraw = function() {};

/**
 * @constructor
 * @struct
 * @param {!CanvasGauges.GenericOptions} options
 * @param {string} element
 * @param {string} type
 */
CanvasGauges.DomObserver = function(options, element, type) {};
 /** @type {!CanvasGauges.BaseGauge} */
CanvasGauges.DomObserver.prototype.Type;
 /** @type {boolean} */
CanvasGauges.DomObserver.prototype.mutationsObserved;
 /** @type {boolean} */
CanvasGauges.DomObserver.prototype.isObservable;
 /** @type {!CanvasGauges.GenericOptions} */
CanvasGauges.DomObserver.prototype.options;
 /** @type {string} */
CanvasGauges.DomObserver.prototype.element;
 /** @type {string} */
CanvasGauges.DomObserver.prototype.type;

/**
 * @param {(!HTMLElement|!Node)} node
 * @return {boolean}
 */
CanvasGauges.DomObserver.prototype.isValidNode = function(node) {};

/**
 * @return {?}
 */
CanvasGauges.DomObserver.prototype.traverse = function() {};

/**
 * @param {!Array<!MutationRecord>} records
 * @return {?}
 */
CanvasGauges.DomObserver.prototype.observe = function(records) {};

/**
 * @param {(!HTMLElement|!Node)} node
 * @return {!CanvasGauges.BaseGauge}
 */
CanvasGauges.DomObserver.prototype.process = function(node) {};

/**
 * @param {?} value
 * @return {?}
 */
CanvasGauges.DomObserver.parse = function(value) {};

/**
 * @param {string} camelCase
 * @return {string}
 */
CanvasGauges.DomObserver.toDashed = function(camelCase) {};

/**
 * @param {string} str
 * @return {string}
 */
CanvasGauges.DomObserver.toAttributeName = function(str) {};

/**
 * @param {!Function} handler
 * @return {?}
 */
CanvasGauges.DomObserver.domReady = function(handler) {};

/**
 * @constructor
 * @struct
 * @param {!CanvasGauges.GenericOptions} options
 */
CanvasGauges.BaseGauge = function(options) {};
 /** @type {!CanvasGauges.BaseGauge} */
CanvasGauges.BaseGauge.prototype.type;
 /** @type {!CanvasGauges.GenericOptions} */
CanvasGauges.BaseGauge.prototype.options;
 /** @type {!CanvasGauges.SmartCanvas} */
CanvasGauges.BaseGauge.prototype.canvas;
 /** @type {!CanvasGauges.Animation} */
CanvasGauges.BaseGauge.prototype.animation;
 /** @type {number} */
CanvasGauges.BaseGauge.prototype.value;
 /** @type {number} */
CanvasGauges.BaseGauge.version;

/**
 * @param {!CanvasGauges.GenericOptions} options
 * @return {!CanvasGauges.BaseGauge}
 */
CanvasGauges.BaseGauge.prototype.update = function(options) {};

/**
 * @return {?}
 */
CanvasGauges.BaseGauge.prototype.destroy = function() {};

/**
 * @abstract
 * @return {!CanvasGauges.BaseGauge}
 */
CanvasGauges.BaseGauge.prototype.draw = function() {};

/**
 * @param {string} type
 * @param {!CanvasGauges.GenericOptions} options
 * @return {?}
 */
CanvasGauges.BaseGauge.initialize = function(type, options) {};

/**
 * @param {!HTMLElement} element
 * @return {?}
 */
CanvasGauges.BaseGauge.fromElement = function(element) {};

/**
 * @param {number} value
 * @return {number}
 */
CanvasGauges.BaseGauge.ensureValue = function(value) {};

/**
 * @constructor
 * @struct
 * @param {!CanvasGauges.RadialGaugeOptions} options
 */
CanvasGauges.RadialGauge = function(options) {};
 /** @type {!CanvasGauges.RadialGauge} */
CanvasGauges.RadialGauge.prototype.type;
 /** @type {!CanvasGauges.RadialGaugeOptions} */
CanvasGauges.RadialGauge.prototype.options;

/**
 * @return {!CanvasGauges.RadialGauge}
 */
CanvasGauges.RadialGauge.prototype.draw = function() {};

/**
 * @constructor
 * @struct
 * @param {!CanvasGauges.LinearGaugeOptions} options
 */
CanvasGauges.LinearGauge = function(options) {};
 /** @type {!CanvasGauges.LinearGauge} */
CanvasGauges.LinearGauge.prototype.type;
 /** @type {!CanvasGauges.LinearGaugeOptions} */
CanvasGauges.LinearGauge.prototype.options;

/**
 * @return {!CanvasGauges.LinearGauge}
 */
CanvasGauges.LinearGauge.prototype.draw = function() {};
/**
 * @record
 * @struct
 */
CanvasGauges.Collection = function() {};
 /** @type {function((string|number)): !CanvasGauges.BaseGauge} */
CanvasGauges.Collection.prototype.get;
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "canvas-gauges"
/** @const */
tsickle_declare_module.canvas_gauges = {};

/* TODO: ExportAssignment in tsickle_declare_module.canvas_gauges */
 /** @type {!CanvasGauges.Collection} */
Document.prototype.gauges;
 /** @type {!CanvasGauges.BaseGauge} */
Window.prototype.BaseGauge;
 /** @type {!CanvasGauges.RadialGauge} */
Window.prototype.RadialGauge;
 /** @type {!CanvasGauges.LinearGauge} */
Window.prototype.LinearGauge;
