/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/collections/index.d.ts:
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "collections/sorted-set"
/** @const */
tsickle_declare_module.collections_sorted_set = {};
/** @const */
tsickle_declare_module.collections_sorted_set.internal = {};
/**
 * @constructor
 * @struct
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet = function() {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.union = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.intersection = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.difference = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.symmetricDifference = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.remove = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.contains = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.toggle = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.addEach = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.deleteEach = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.deleteAll = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.findValue = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.iterator = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.forEach = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.map = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.filter = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.group = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.some = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.every = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.any = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.all = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.only = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.sorted = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.reversed = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.join = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.sum = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.average = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.zip = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.enumerate = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.concat = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.flatten = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.toArray = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.toObject = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.toJSON = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.equals = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.clone = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.contentCompare = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.contentEquals = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.sortedSetLog = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.addRangeChangeListener = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.removeRangeChangeListener = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.dispatchRangeChange = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.addBeforeRangeChangeListener = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.removeBeforeRangeChangeListener = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.dispatchBeforeRangeChange = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.addOwnPropertyChangeListener = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.addBeforeOwnPropertyChangeListener = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.removeOwnPropertyChangeListener = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.removeBeforeOwnPropertyChangeListener = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.dispatchOwnPropertyChange = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.dispatchBeforeOwnPropertyChange = function(plus) {};

/**
 * @param {...?} plus
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.AbstractSet.prototype.makePropertyObservable = function(plus) {};
/**
 * @constructor
 * @struct
 */
tsickle_declare_module.collections_sorted_set.internal.Node = function() {};

/**
 * @param {function(?, ?, ?, ?): ?} cb
 * @param {?} basis
 * @param {number} index
 * @param {?} thisp
 * @param {?} tree
 * @param {number} depth
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.Node.prototype.reduce = function(cb, basis, index, thisp, tree, depth) {};

/**
 * @param {...?} plus
 * @return {void}
 */
tsickle_declare_module.collections_sorted_set.internal.Node.prototype.touch = function(plus) {};

/**
 * @param {...?} plus
 * @return {number}
 */
tsickle_declare_module.collections_sorted_set.internal.Node.prototype.checkIntegrity = function(plus) {};

/**
 * @param {...?} plus
 * @return {!internal.Node}
 */
tsickle_declare_module.collections_sorted_set.internal.Node.prototype.getNext = function(plus) {};

/**
 * @param {...?} plus
 * @return {!internal.Node}
 */
tsickle_declare_module.collections_sorted_set.internal.Node.prototype.getPrevious = function(plus) {};

/**
 * @param {...?} plus
 * @return {string}
 */
tsickle_declare_module.collections_sorted_set.internal.Node.prototype.summary = function(plus) {};

/**
 * @param {?} charmap
 * @param {?} logNode
 * @param {?} log
 * @param {?} logAbove
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.Node.prototype.log = function(charmap, logNode, log, logAbove) {};
/**
 * @constructor
 * @struct
 */
tsickle_declare_module.collections_sorted_set.internal.Iterator = function() {};

/**
 * @return {{done: boolean, value: T}}
 */
tsickle_declare_module.collections_sorted_set.internal.Iterator.prototype.next = function() {};

/**
 * @constructor
 * @struct
 * @param {!Array<T>=} values
 * @param {function(T, T): boolean=} equals
 * @param {function(T, T): number=} compare
 * @param {?=} getDefault
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet = function(values, equals, compare, getDefault) {};

/**
 * @param {!Array<T>=} values
 * @return {!internal.SortedSet}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.constructClone = function(values) {};

/**
 * @param {T} value
 * @return {boolean}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.add = function(value) {};

/**
 * @return {void}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.clear = function() {};

/**
 * @param {T} value
 * @return {boolean}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype['delete'] = function(value) {};

/**
 * @param {T} value
 * @return {!internal.Node<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.find = function(value) {};

/**
 * @param {!internal.Node<T>=} n
 * @return {!internal.Node<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.findGreatest = function(n) {};

/**
 * @param {T} value
 * @return {!internal.Node<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.findGreatestLessThan = function(value) {};

/**
 * @param {T} value
 * @return {!internal.Node<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.findGreatestLessThanOrEqual = function(value) {};

/**
 * @param {!internal.Node<T>=} n
 * @return {!internal.Node<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.findLeast = function(n) {};

/**
 * @param {T} value
 * @return {!internal.Node<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.findLeastGreaterThan = function(value) {};

/**
 * @param {T} value
 * @return {!internal.Node<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.findLeastGreaterThanOrEqual = function(value) {};

/**
 * @param {!internal.Node<T>=} n
 * @return {T}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.max = function(n) {};

/**
 * @param {!internal.Node<T>=} n
 * @return {T}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.min = function(n) {};

/**
 * @return {T}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.one = function() {};

/**
 * @param {T} elt
 * @return {T}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.get = function(elt) {};

/**
 * @param {T} elt
 * @return {boolean}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.has = function(elt) {};

/**
 * @param {T} value
 * @return {number}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.indexOf = function(value) {};

/**
 * @return {T}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.pop = function() {};

/**
 * @param {...T} rest
 * @return {void}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.push = function(rest) {};

/**
 * @return {T}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.shift = function() {};

/**
 * @param {...T} rest
 * @return {void}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.unshift = function(rest) {};

/**
 * @param {number=} start
 * @param {number=} end
 * @return {!Array<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.slice = function(start, end) {};

/**
 * @param {!internal.Node<T>} start
 * @param {number} length
 * @param {...T} values
 * @return {!Array<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.splice = function(start, length, values) {};

/**
 * @param {number} start
 * @param {number} length
 * @param {!Array<T>=} values
 * @return {!Array<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.swap = function(start, length, values) {};

/**
 * @param {T} value
 * @return {void}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.splay = function(value) {};

/**
 * @param {number} index
 * @return {boolean}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.splayIndex = function(index) {};

/**
 * @param {function(?, ?, ?, ?): ?} callback
 * @param {?=} basis
 * @param {?=} thisp
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.reduce = function(callback, basis, thisp) {};

/**
 * @param {function(?, ?, ?, ?): ?} callback
 * @param {?=} basis
 * @param {?=} thisp
 * @return {?}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.reduceRight = function(callback, basis, thisp) {};

/**
 * @param {number} start
 * @param {number} stop
 * @return {!internal.Iterator<T>}
 */
tsickle_declare_module.collections_sorted_set.internal.SortedSet.prototype.iterate = function(start, stop) {};

/* TODO: ExportAssignment in tsickle_declare_module.collections_sorted_set */
