/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/content-disposition/index.d.ts:
/** @const */
var contentDisposition = {};
/**
 * @record
 * @struct
 */
contentDisposition.ContentDisposition = function() {};
 /** @type {string} */
contentDisposition.ContentDisposition.prototype.type;
 /** @type {?} */
contentDisposition.ContentDisposition.prototype.parameters;
/**
 * @record
 * @struct
 */
contentDisposition.Options = function() {};
 /** @type {string} */
contentDisposition.Options.prototype.type;
 /** @type {(string|boolean)} */
contentDisposition.Options.prototype.fallback;

/**
 * @param {string} contentDispositionHeader
 * @return {!contentDisposition.ContentDisposition}
 */
contentDisposition.parse = function(contentDispositionHeader) {};

/**
 * @param {string=} filename
 * @param {!contentDisposition.Options=} options
 * @return {string}
 */
function contentDisposition(filename, options) {}

/* TODO: ExportAssignment in  */
