/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/convert-hrtime/index.d.ts:

/* TODO: ExportAssignment in  */

/**
 * @param {!Array<?>} hrtime
 * @return {!convertHrtime.HRTime}
 */
function convertHrtime(hrtime) {}
/**
 * @record
 * @struct
 */
convertHrtime.HRTime = function() {};
 /** @type {number} */
convertHrtime.HRTime.prototype.seconds;
 /** @type {number} */
convertHrtime.HRTime.prototype.milliseconds;
 /** @type {number} */
convertHrtime.HRTime.prototype.nanoseconds;
