/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/create-error/index.d.ts:

/** @typedef {!Error} */
var Err;
/** @const */
var createError = {};
/**
 * @record
 * @struct
 */
createError.Error = function() {};

/* TODO: ConstructSignature: createError */

/**
 * @template T
 * @param {string|!createError.Error<!Error>=} name_or_Target
 * @param {?|string=} properties_or_name
 * @param {?=} properties
 * @return {!createError.Error<!Error>|T}
 */
function createError(name_or_Target, properties_or_name, properties) {}

/* TODO: ExportAssignment in  */
