/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/debounce/index.d.ts:

/**
 * @template A
 * @param {A} f
 * @param {number=} interval
 * @param {boolean=} immediate
 * @return {?}
 */
function debounce(f, interval, immediate) {}

/* TODO: ExportAssignment in  */
