/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/decay/index.d.ts:

/**
 * Creates a function to rank posts using Reddit's "hot" algorithm.
 * @param {number=} decay controls how quickly rankings drop with time
 * @return {?} calculator function
 */
function redditHot(decay) {}

/**
 * Creates a function to rank posts using the Hacker News "hot" algorithm.
 * @param {number=} gravity controls how quickly rankings drop with time
 * @return {?} calculator function
 */
function hackerHot(gravity) {}

/**
 * Creates a function to rank posts using the Wilson score interval sort (Reddit's "best"
 * algorithm).
 * @see {\@link https://redditblog.com/2009/10/15/reddits-new-comment-sorting-system/ Reddit's writeup}
 * @param {number=} confidence statistical confidence
 * @return {?} calculator function
 */
function wilsonScore(confidence) {}

/** @typedef {?} */
var RedditHotFunction;

/** @typedef {?} */
var HackerNewsHotFunction;

/** @typedef {?} */
var WilsonScoreFunction;
