/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/detect-indent v0/index.d.ts:

/** @typedef {?} */
var DetectIndent;
 /** @type {?} */
var _;

/* TODO: ExportAssignment in  */
