/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/diff2html/index.d.ts:
/** @const */
var Diff2Html = {};
/**
 * @record
 * @struct
 */
Diff2Html.Options = function() {};
 /** @type {string} */
Diff2Html.Options.prototype.inputFormat;
 /** @type {string} */
Diff2Html.Options.prototype.outputFormat;
 /** @type {boolean} */
Diff2Html.Options.prototype.showFiles;
 /** @type {string} */
Diff2Html.Options.prototype.matching;
 /** @type {boolean} */
Diff2Html.Options.prototype.synchronisedScroll;
 /** @type {number} */
Diff2Html.Options.prototype.matchWordsThreshold;
 /** @type {number} */
Diff2Html.Options.prototype.matchingMaxComparisons;
/**
 * @record
 * @struct
 */
Diff2Html.Line = function() {};
 /** @type {string} */
Diff2Html.Line.prototype.content;
 /** @type {string} */
Diff2Html.Line.prototype.type;
 /** @type {number} */
Diff2Html.Line.prototype.oldNumber;
 /** @type {number} */
Diff2Html.Line.prototype.newNumber;
/**
 * @record
 * @struct
 */
Diff2Html.Block = function() {};
 /** @type {number} */
Diff2Html.Block.prototype.oldStartLine;
 /** @type {number} */
Diff2Html.Block.prototype.oldStartLine2;
 /** @type {number} */
Diff2Html.Block.prototype.newStartLine;
 /** @type {string} */
Diff2Html.Block.prototype.header;
 /** @type {!Array<!Diff2Html.Line>} */
Diff2Html.Block.prototype.lines;
/**
 * @record
 * @struct
 */
Diff2Html.Result = function() {};
 /** @type {number} */
Diff2Html.Result.prototype.addedLines;
 /** @type {number} */
Diff2Html.Result.prototype.deletedLines;
 /** @type {boolean} */
Diff2Html.Result.prototype.isCombined;
 /** @type {boolean} */
Diff2Html.Result.prototype.isGitDiff;
 /** @type {string} */
Diff2Html.Result.prototype.oldName;
 /** @type {string} */
Diff2Html.Result.prototype.newName;
 /** @type {string} */
Diff2Html.Result.prototype.language;
 /** @type {!Array<!Diff2Html.Block>} */
Diff2Html.Result.prototype.blocks;
 /** @type {string} */
Diff2Html.Result.prototype.oldMode;
 /** @type {string} */
Diff2Html.Result.prototype.newMode;
 /** @type {string} */
Diff2Html.Result.prototype.deletedFileMode;
 /** @type {string} */
Diff2Html.Result.prototype.newFileMode;
 /** @type {boolean} */
Diff2Html.Result.prototype.isDeleted;
 /** @type {boolean} */
Diff2Html.Result.prototype.isNew;
 /** @type {boolean} */
Diff2Html.Result.prototype.isCopy;
 /** @type {boolean} */
Diff2Html.Result.prototype.isRename;
 /** @type {number} */
Diff2Html.Result.prototype.unchangedPercentage;
 /** @type {number} */
Diff2Html.Result.prototype.changedPercentage;
 /** @type {string} */
Diff2Html.Result.prototype.checksumBefore;
 /** @type {string} */
Diff2Html.Result.prototype.checksumAfter;
 /** @type {string} */
Diff2Html.Result.prototype.mode;
/**
 * @record
 * @struct
 */
Diff2Html.Diff2Html = function() {};

/**
 * @param {string} input
 * @param {!Diff2Html.Options=} configuration
 * @return {!Diff2Html.Result}
 */
Diff2Html.Diff2Html.prototype.getJsonFromDiff = function(input, configuration) {};

/**
 * @param {?} input
 * @param {!Diff2Html.Options=} configuration
 * @return {string}
 */
Diff2Html.Diff2Html.prototype.getPrettyHtml = function(input, configuration) {};
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "diff2html"
/** @const */
tsickle_declare_module.diff_html = {};
 /** @type {{Diff2Html: !Diff2Html.Diff2Html}} */
tsickle_declare_module.diff_html.d2h;

/* TODO: ExportAssignment in tsickle_declare_module.diff_html */
