/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/dotenv-safe/index.d.ts:

/* TODO: ImportEqualsDeclaration in  */
/**
 * @record
 * @struct
 */
function MissingEnvVarsError() {}
 /** @type {string} */
MissingEnvVarsError.prototype.sample;
 /** @type {!Array<string>} */
MissingEnvVarsError.prototype.missing;

/**
 * Loads environment variables file into 'process.env'.
 * 
 * 
 * @throws MissingEnvVarsError
 * 
 * @param {?=} options
 * @return {?} env.DotenvResult
 */
function load(options) {}
