/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/htmlhint/index.d.ts:
/**
 * @record
 * @struct
 */
function LintResult() {}
 /** @type {string} */
LintResult.prototype.evidence;
 /** @type {number} */
LintResult.prototype.line;
 /** @type {number} */
LintResult.prototype.col;
 /** @type {string} */
LintResult.prototype.message;
 /** @type {?} */
LintResult.prototype.rule;
/**
 * @record
 * @struct
 */
function FormatOptions() {}
 /** @type {number} */
FormatOptions.prototype.indent;
 /** @type {boolean} */
FormatOptions.prototype.colors;
/**
 * @record
 * @struct
 */
function Rule() {}
 /** @type {string} */
Rule.prototype.id;
 /** @type {string} */
Rule.prototype.description;
 /** @type {string} */
Rule.prototype.link;
/**
 * @record
 * @struct
 */
function RuleSet() {}

/* TODO: IndexSignature:  */
/** @const */
var HTMLHint = {};

/**
 * @param {string} fileContent
 * @param {?=} ruleSet
 * @return {!Array<?>}
 */
HTMLHint.verify = function(fileContent, ruleSet) {};

/**
 * @param {!Array<?>} arrMessages
 * @param {?=} options
 * @return {!Array<string>}
 */
HTMLHint.format = function(arrMessages, options) {};
