/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/is-windows/index.d.ts:

/**
 * @return {boolean}
 */
function isWindows() {}

/* TODO: ExportAssignment in  */
