/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/jquery.placeholder/index.d.ts:

/**
 * @param {{customClass: string}=} options
 * @return {?<!HTMLElement>}
 */
JQuery.prototype.placeholder = function(options) {};
