/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/jquery.flagstrap/index.d.ts:
/** @const */
var jQueryFlagStrap = {};
/**
 * @record
 * @struct
 */
jQueryFlagStrap.FlagStrapOptions = function() {};
 /** @type {string} */
jQueryFlagStrap.FlagStrapOptions.prototype.inputName;
 /** @type {string} */
jQueryFlagStrap.FlagStrapOptions.prototype.inputId;
 /** @type {string} */
jQueryFlagStrap.FlagStrapOptions.prototype.buttonSize;
 /** @type {string} */
jQueryFlagStrap.FlagStrapOptions.prototype.buttonType;
 /** @type {string} */
jQueryFlagStrap.FlagStrapOptions.prototype.labelMargin;
 /** @type {boolean} */
jQueryFlagStrap.FlagStrapOptions.prototype.scrollable;
 /** @type {string} */
jQueryFlagStrap.FlagStrapOptions.prototype.scrollableHeight;
 /** @type {!Object} */
jQueryFlagStrap.FlagStrapOptions.prototype.countries;
 /** @type {(boolean|!jQueryFlagStrap.FlagStrapPlaceholderOptions)} */
jQueryFlagStrap.FlagStrapOptions.prototype.placeholder;

/**
 * Default: null
 * This callback gets called each time the select is changed. It receives two parameters, the new value, and the select element.
 * @param {?} value
 * @param {?} element
 * @return {void}
 */
jQueryFlagStrap.FlagStrapOptions.prototype.onSelect = function(value, element) {};
/**
 * @record
 * @struct
 */
jQueryFlagStrap.FlagStrapStatic = function() {};
 /** @type {void} */
jQueryFlagStrap.FlagStrapStatic.prototype.flagStrap;
/**
 * @record
 * @struct
 */
jQueryFlagStrap.FlagStrapPlaceholderOptions = function() {};
 /** @type {string} */
jQueryFlagStrap.FlagStrapPlaceholderOptions.prototype.value;
 /** @type {string} */
jQueryFlagStrap.FlagStrapPlaceholderOptions.prototype.text;

/**
 * A lightwieght jQuery plugin for creating Bootstrap 3 compatible country select boxes with flags.
 * @param {!jQueryFlagStrap.FlagStrapOptions=} options
 * @return {void}
 */
JQuery.prototype.flagStrap = function(options) {};
