/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/jquery.timepicker/index.d.ts:
/**
 * @record
 * @struct
 */
function TimePickerHour() {}
 /** @type {number} */
TimePickerHour.prototype.starts;
 /** @type {number} */
TimePickerHour.prototype.ends;
/**
 * @record
 * @struct
 */
function TimePickerMinutes() {}
 /** @type {number} */
TimePickerMinutes.prototype.starts;
 /** @type {number} */
TimePickerMinutes.prototype.ends;
 /** @type {number} */
TimePickerMinutes.prototype.interval;
/**
 * @record
 * @struct
 */
function TimePickerOptions() {}
 /** @type {string} */
TimePickerOptions.prototype.showOn;
 /** @type {string} */
TimePickerOptions.prototype.button;
 /** @type {string} */
TimePickerOptions.prototype.hourText;
 /** @type {string} */
TimePickerOptions.prototype.minuteText;
 /** @type {!Array<?>} */
TimePickerOptions.prototype.amPmText;
 /** @type {string} */
TimePickerOptions.prototype.showAnim;
 /** @type {?} */
TimePickerOptions.prototype.showOptions;
 /** @type {string} */
TimePickerOptions.prototype.appendText;
 /** @type {function(): ?} */
TimePickerOptions.prototype.beforeShow;
 /** @type {function(string, ?): ?} */
TimePickerOptions.prototype.onSelect;
 /** @type {function(string, ?): ?} */
TimePickerOptions.prototype.onClose;
 /** @type {string} */
TimePickerOptions.prototype.timeSeparator;
 /** @type {string} */
TimePickerOptions.prototype.periodSeparator;
 /** @type {boolean} */
TimePickerOptions.prototype.showPeriod;
 /** @type {boolean} */
TimePickerOptions.prototype.showPeriodLabels;
 /** @type {boolean} */
TimePickerOptions.prototype.showLeadingZero;
 /** @type {boolean} */
TimePickerOptions.prototype.showMinutesLeadingZero;
 /** @type {string} */
TimePickerOptions.prototype.altField;
 /** @type {string} */
TimePickerOptions.prototype.defaultTime;
 /** @type {string} */
TimePickerOptions.prototype.myPosition;
 /** @type {string} */
TimePickerOptions.prototype.atPosition;
 /** @type {function(): ?} */
TimePickerOptions.prototype.onHourShow;
 /** @type {function(): ?} */
TimePickerOptions.prototype.onMinuteShow;
 /** @type {!TimePickerHour} */
TimePickerOptions.prototype.hours;
 /** @type {!TimePickerMinutes} */
TimePickerOptions.prototype.minutes;
 /** @type {number} */
TimePickerOptions.prototype.rows;
 /** @type {boolean} */
TimePickerOptions.prototype.showHours;
 /** @type {boolean} */
TimePickerOptions.prototype.showMinutes;
 /** @type {boolean} */
TimePickerOptions.prototype.optionalMinutes;
 /** @type {boolean} */
TimePickerOptions.prototype.showCloseButton;
 /** @type {string} */
TimePickerOptions.prototype.closeButtonText;
 /** @type {boolean} */
TimePickerOptions.prototype.showNowButton;
 /** @type {string} */
TimePickerOptions.prototype.nowButtonText;
 /** @type {boolean} */
TimePickerOptions.prototype.showDeselectButton;
 /** @type {string} */
TimePickerOptions.prototype.deselectButtonText;

/**
 * @param {string|!TimePickerOptions=} methodName_or_optionLiteral_or_options
 * @param {?|string=} methodParameter_or_optionName
 * @return {?<!HTMLElement>|string|!Date|number|?}
 */
JQuery.prototype.timepicker = function(methodName_or_optionLiteral_or_options, methodParameter_or_optionName) {};
