/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/koa-logger/index.d.ts:

/* TODO: ImportDeclaration in  */

/**
 * @return {function(!Application.Context, function(): !Promise<?>): ?}
 */
function KoaLogger() {}

/* TODO: ExportAssignment in  */
