/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/lodash.negate/index.d.ts:

/* TODO: ImportDeclaration in  */

/* TODO: ExportAssignment in  */
