/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/lowlight/index.d.ts:
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "lowlight"
/** @const */
tsickle_declare_module.lowlight = {};

/* TODO: ExportDeclaration in tsickle_declare_module.lowlight */
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "lowlight/lib/core"
/** @const */
tsickle_declare_module.lowlight_lib_core = {};

/**
 * @param {string} language
 * @param {string} value
 * @param {!lowlight.HighlightOptions=} options
 * @return {!lowlight.HighlightResult}
 */
tsickle_declare_module.lowlight_lib_core.highlight = function(language, value, options) {};

/**
 * @param {string} value
 * @param {!lowlight.HighlightAutoOptions=} options
 * @return {!lowlight.HighlightAutoResult}
 */
tsickle_declare_module.lowlight_lib_core.highlightAuto = function(value, options) {};

/**
 * @param {string} name
 * @param {!Function} syntax
 * @return {void}
 */
tsickle_declare_module.lowlight_lib_core.registerLanguage = function(name, syntax) {};
/** @const */
var lowlight = {};
/** @const */
lowlight.AST = {};
/** @const */
lowlight.AST.Unist = {};
/**
 * @record
 * @struct
 */
lowlight.AST.Unist.Data = function() {};

/* TODO: IndexSignature: lowlight.AST.Unist */
/**
 * @record
 * @struct
 */
lowlight.AST.Unist.Position = function() {};
 /** @type {number} */
lowlight.AST.Unist.Position.prototype.line;
 /** @type {number} */
lowlight.AST.Unist.Position.prototype.column;
 /** @type {number} */
lowlight.AST.Unist.Position.prototype.offset;
/**
 * @record
 * @struct
 */
lowlight.AST.Unist.Location = function() {};
 /** @type {!lowlight.AST.Unist.Position} */
lowlight.AST.Unist.Location.prototype.start;
 /** @type {!lowlight.AST.Unist.Position} */
lowlight.AST.Unist.Location.prototype.end;
 /** @type {!Array<number>} */
lowlight.AST.Unist.Location.prototype.indent;
/**
 * @record
 * @struct
 */
lowlight.AST.Unist.Node = function() {};
 /** @type {string} */
lowlight.AST.Unist.Node.prototype.type;
 /** @type {!lowlight.AST.Unist.Data} */
lowlight.AST.Unist.Node.prototype.data;
 /** @type {!lowlight.AST.Unist.Location} */
lowlight.AST.Unist.Node.prototype.position;
/**
 * @extends {lowlight.AST.Unist.Node}
 * @record
 * @struct
 */
lowlight.AST.Unist.Parent = function() {};
 /** @type {!Array<!lowlight.AST.Unist.Node>} */
lowlight.AST.Unist.Parent.prototype.children;
/**
 * @extends {lowlight.AST.Unist.Node}
 * @record
 * @struct
 */
lowlight.AST.Unist.Text = function() {};
 /** @type {string} */
lowlight.AST.Unist.Text.prototype.value;
/**
 * @record
 * @struct
 */
lowlight.AST.Properties = function() {};

/* TODO: IndexSignature: lowlight.AST */
/**
 * @extends {lowlight.AST.Unist.Parent}
 * @record
 * @struct
 */
lowlight.AST.Root = function() {};
 /** @type {string} */
lowlight.AST.Root.prototype.type;
/**
 * @extends {lowlight.AST.Unist.Parent}
 * @record
 * @struct
 */
lowlight.AST.Element = function() {};
 /** @type {string} */
lowlight.AST.Element.prototype.type;
 /** @type {string} */
lowlight.AST.Element.prototype.tagName;
 /** @type {!lowlight.AST.Properties} */
lowlight.AST.Element.prototype.properties;
/**
 * @extends {lowlight.AST.Unist.Node}
 * @record
 * @struct
 */
lowlight.AST.Doctype = function() {};
 /** @type {string} */
lowlight.AST.Doctype.prototype.type;
 /** @type {string} */
lowlight.AST.Doctype.prototype.name;
 /** @type {string} */
lowlight.AST.Doctype.prototype.public;
 /** @type {string} */
lowlight.AST.Doctype.prototype.system;
/**
 * @extends {lowlight.AST.Unist.Text}
 * @record
 * @struct
 */
lowlight.AST.Comment = function() {};
 /** @type {string} */
lowlight.AST.Comment.prototype.type;
/**
 * @extends {lowlight.AST.Unist.Text}
 * @record
 * @struct
 */
lowlight.AST.Text = function() {};
 /** @type {string} */
lowlight.AST.Text.prototype.type;

/** @typedef {(!lowlight.AST.Root|!lowlight.AST.Element|!lowlight.AST.Doctype|!lowlight.AST.Comment|!lowlight.AST.Text)} */
lowlight.HastNode;
/**
 * @record
 * @struct
 */
lowlight.HighlightOptions = function() {};
 /** @type {string} */
lowlight.HighlightOptions.prototype.prefix;
/**
 * @extends {lowlight.HighlightOptions}
 * @record
 * @struct
 */
lowlight.HighlightAutoOptions = function() {};
 /** @type {!Array<string>} */
lowlight.HighlightAutoOptions.prototype.subset;
/**
 * @record
 * @struct
 */
lowlight.HighlightResult = function() {};
 /** @type {number} */
lowlight.HighlightResult.prototype.relevance;
 /** @type {string} */
lowlight.HighlightResult.prototype.language;
 /** @type {!Array<(!lowlight.AST.Root|!lowlight.AST.Element|!lowlight.AST.Doctype|!lowlight.AST.Comment|!lowlight.AST.Text)>} */
lowlight.HighlightResult.prototype.value;
/**
 * @extends {lowlight.HighlightResult}
 * @record
 * @struct
 */
lowlight.HighlightAutoResult = function() {};
 /** @type {!lowlight.HighlightAutoResult} */
lowlight.HighlightAutoResult.prototype.secondBest;
