/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/markitup/index.d.ts:
/** @const */
var MarkItUp = {};
/**
 * @record
 * @struct
 */
MarkItUp.Options = function() {};
 /** @type {string} */
MarkItUp.Options.prototype.nameSpace;
 /** @type {boolean} */
MarkItUp.Options.prototype.resizeHandle;
 /** @type {string} */
MarkItUp.Options.prototype.previewInWindow;
 /** @type {boolean} */
MarkItUp.Options.prototype.previewAutoRefresh;
 /** @type {string} */
MarkItUp.Options.prototype.previewParserPath;
 /** @type {string} */
MarkItUp.Options.prototype.previewParserVar;
 /** @type {string} */
MarkItUp.Options.prototype.previewTemplatePath;
 /** @type {boolean} */
MarkItUp.Options.prototype.previewParser;
 /** @type {string} */
MarkItUp.Options.prototype.previewPosition;
 /** @type {!MarkItUp.MarkupSet} */
MarkItUp.Options.prototype.onEnter;
 /** @type {!MarkItUp.MarkupSet} */
MarkItUp.Options.prototype.onCtrlEnter;
 /** @type {!MarkItUp.MarkupSet} */
MarkItUp.Options.prototype.onShiftEnter;
 /** @type {!MarkItUp.MarkupSet} */
MarkItUp.Options.prototype.onTab;
 /** @type {function(!MarkItUp.MarkupSet): string} */
MarkItUp.Options.prototype.beforeInsert;
 /** @type {function(!MarkItUp.MarkupSet): string} */
MarkItUp.Options.prototype.afterInsert;
 /** @type {!Array<!MarkItUp.MarkupSet>} */
MarkItUp.Options.prototype.markupSet;
/**
 * @record
 * @struct
 */
MarkItUp.MarkupSet = function() {};
 /** @type {string} */
MarkItUp.MarkupSet.prototype.name;
 /** @type {string} */
MarkItUp.MarkupSet.prototype.className;
 /** @type {string} */
MarkItUp.MarkupSet.prototype.key;
 /** @type {(string|function(!MarkItUp.MarkupSet): string)} */
MarkItUp.MarkupSet.prototype.openWith;
 /** @type {(string|function(!MarkItUp.MarkupSet): string)} */
MarkItUp.MarkupSet.prototype.closeWith;
 /** @type {(string|function(!MarkItUp.MarkupSet): string)} */
MarkItUp.MarkupSet.prototype.replaceWith;
 /** @type {(string|function(!MarkItUp.MarkupSet): string)} */
MarkItUp.MarkupSet.prototype.openBlockWith;
 /** @type {(string|function(!MarkItUp.MarkupSet): string)} */
MarkItUp.MarkupSet.prototype.closeBlockWith;
 /** @type {boolean} */
MarkItUp.MarkupSet.prototype.multiline;
 /** @type {(string|function(!MarkItUp.MarkupSet): string)} */
MarkItUp.MarkupSet.prototype.placeHolder;
 /** @type {function(!MarkItUp.MarkupSet): string} */
MarkItUp.MarkupSet.prototype.beforeInsert;
 /** @type {function(!MarkItUp.MarkupSet): string} */
MarkItUp.MarkupSet.prototype.afterInsert;
 /** @type {function(!MarkItUp.MarkupSet): string} */
MarkItUp.MarkupSet.prototype.beforeMultiInsert;
 /** @type {function(!MarkItUp.MarkupSet): string} */
MarkItUp.MarkupSet.prototype.afterMultiInsert;
 /** @type {!Array<!MarkItUp.MarkupSet>} */
MarkItUp.MarkupSet.prototype.dropMenu;
 /** @type {boolean} */
MarkItUp.MarkupSet.prototype.keepDefault;
 /** @type {string} */
MarkItUp.MarkupSet.prototype.selection;
 /** @type {!HTMLElement} */
MarkItUp.MarkupSet.prototype.textarea;
 /** @type {number} */
MarkItUp.MarkupSet.prototype.caretPosition;
 /** @type {number} */
MarkItUp.MarkupSet.prototype.scrollPosition;
 /** @type {number} */
MarkItUp.MarkupSet.prototype.line;
 /** @type {boolean} */
MarkItUp.MarkupSet.prototype.ctrlKey;
 /** @type {boolean} */
MarkItUp.MarkupSet.prototype.shiftKey;
 /** @type {boolean} */
MarkItUp.MarkupSet.prototype.altKey;
 /** @type {string} */
MarkItUp.MarkupSet.prototype.separator;
/**
 * @record
 * @struct
 */
MarkItUp.Static = function() {};

/* TODO: CallSignature: MarkItUp */

/* TODO: CallSignature: MarkItUp */
 /** @type {!MarkItUp.Static} */
JQueryStatic.prototype.markItUp;

/**
 * @param {!MarkItUp.Options=} settings
 * @param {!MarkItUp.Options=} extraSettings
 * @return {?<!HTMLElement>}
 */
JQuery.prototype.markItUp = function(settings, extraSettings) {};

/**
 * @return {?<!HTMLElement>}
 */
JQuery.prototype.markItUpRemove = function() {};
