/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/nodemailer-pickup-transport/index.d.ts:

/* TODO: ImportEqualsDeclaration in  */
/** @const */
var PickupTransport = {};
/**
 * @record
 * @struct
 */
PickupTransport.Options = function() {};
 /** @type {string} */
PickupTransport.Options.prototype.directory;

/**
 * @param {!PickupTransport.Options} options
 * @return {?}
 */
function PickupTransport(options) {}

/* TODO: ExportAssignment in  */
