/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/p-throttle/index.d.ts:

/* TODO: ExportAssignment in  */

/**
 * @template R, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10
 * @param {function(): (R|!PromiseLike<R>)|function(T1): (R|!PromiseLike<R>)|function(T1, T2): (R|!PromiseLike<R>)|function(T1, T2, T3): (R|!PromiseLike<R>)|function(T1, T2, T3, T4): (R|!PromiseLike<R>)|function(T1, T2, T3, T4, T5): (R|!PromiseLike<R>)|function(T1, T2, T3, T4, T5, T6): (R|!PromiseLike<R>)|function(T1, T2, T3, T4, T5, T6, T7): (R|!PromiseLike<R>)|function(T1, T2, T3, T4, T5, T6, T7, T8): (R|!PromiseLike<R>)|function(T1, T2, T3, T4, T5, T6, T7, T8, T9): (R|!PromiseLike<R>)|function(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10): (R|!PromiseLike<R>)|function(!Array<?>): (R|!PromiseLike<R>)} fn
 * @param {number} limit
 * @param {number} interval
 * @return {?}
 */
function pThrottle(fn, limit, interval) {}

/**
 * @constructor
 * @struct
 */
pThrottle.AbortError = function() {};
 /** @type {string} */
pThrottle.AbortError.prototype.name;
