/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/prompt-sync-history/index.d.ts:

/* TODO: ImportDeclaration in  */
/** @const */
var history = {};

/**
 * @param {string=} file
 * @param {number=} max
 * @return {!PromptSync.History}
 */
function history(file, max) {}

/* TODO: ExportAssignment in  */
