/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/react-recaptcha/index.d.ts:

/* TODO: ImportDeclaration in  */

/* TODO: ExportAssignment in  */
/**
 * @record
 * @struct
 */
function RecaptchaProps() {}
 /** @type {string} */
RecaptchaProps.prototype.className;
 /** @type {string} */
RecaptchaProps.prototype.elementID;
 /** @type {string} */
RecaptchaProps.prototype.expiredCallbackName;
 /** @type {string} */
RecaptchaProps.prototype.onloadCallbackName;
 /** @type {string} */
RecaptchaProps.prototype.render;
 /** @type {string} */
RecaptchaProps.prototype.size;
 /** @type {string} */
RecaptchaProps.prototype.tabindex;
 /** @type {string} */
RecaptchaProps.prototype.theme;
 /** @type {string} */
RecaptchaProps.prototype.type;
 /** @type {string} */
RecaptchaProps.prototype.verifyCallbackName;
 /** @type {string} */
RecaptchaProps.prototype.sitekey;

/**
 * @return {?}
 */
RecaptchaProps.prototype.expiredCallback = function() {};

/**
 * @return {?}
 */
RecaptchaProps.prototype.onloadCallback = function() {};

/**
 * @param {string} response
 * @return {?}
 */
RecaptchaProps.prototype.verifyCallback = function(response) {};
/**
 * @extends {Component}
 * @constructor
 * @struct
 */
function Recaptcha() {}
 /** @type {?} */
Recaptcha.propTypes;
 /** @type {?} */
Recaptcha.defaultProps;
