/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/react-flex/index.d.ts:

/* TODO: ImportDeclaration in  */
/**
 * @record
 * @struct
 */
function CommonFlexProps() {}
 /** @type {?} */
CommonFlexProps.prototype.style;
 /** @type {boolean} */
CommonFlexProps.prototype.inline;
 /** @type {boolean} */
CommonFlexProps.prototype.row;
 /** @type {boolean} */
CommonFlexProps.prototype.column;
 /** @type {boolean} */
CommonFlexProps.prototype.reverse;
 /** @type {boolean} */
CommonFlexProps.prototype.wrap;
 /** @type {(string|number|boolean)} */
CommonFlexProps.prototype.flex;
 /** @type {string} */
CommonFlexProps.prototype.alignItems;
 /** @type {string} */
CommonFlexProps.prototype.justifyContent;
 /** @type {string} */
CommonFlexProps.prototype.alignContent;
 /** @type {string} */
CommonFlexProps.prototype.display;
/**
 * @extends {React.Props}
 * @extends {CommonFlexProps}
 * @record
 * @struct
 */
function FlexProps() {}
/**
 * @constructor
 * @struct
 */
function Flex() {}
/**
 * @extends {React.Props}
 * @extends {CommonFlexProps}
 * @record
 * @struct
 */
function ItemProps() {}
 /** @type {(string|number|boolean)} */
ItemProps.prototype.flexGrow;
 /** @type {(string|number)} */
ItemProps.prototype.flexShrink;
 /** @type {(number|string)} */
ItemProps.prototype.flexBasis;
/**
 * @constructor
 * @struct
 */
function Item() {}
