/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/react-burger-menu/index.d.ts:

/* TODO: ImportDeclaration in  */
/**
 * @record
 * @struct
 */
function Props() {}
 /** @type {string} */
Props.prototype.burgerBarClassName;
 /** @type {string} */
Props.prototype.burgerButtonClassName;
 /** @type {string} */
Props.prototype.crossButtonClassName;
 /** @type {string} */
Props.prototype.crossClassName;
 /** @type {(boolean|!Element)} */
Props.prototype.customBurgerIcon;
 /** @type {(boolean|!Element)} */
Props.prototype.customCrossIcon;
 /** @type {string} */
Props.prototype.id;
 /** @type {boolean} */
Props.prototype.isOpen;
 /** @type {string} */
Props.prototype.itemListClassName;
 /** @type {string} */
Props.prototype.menuClassName;
 /** @type {string} */
Props.prototype.morphShapeClassName;
 /** @type {boolean} */
Props.prototype.noOverlay;
 /** @type {string} */
Props.prototype.outerContainerId;
 /** @type {string} */
Props.prototype.overlayClassName;
 /** @type {string} */
Props.prototype.pageWrapId;
 /** @type {boolean} */
Props.prototype.right;
 /** @type {?} */
Props.prototype.styles;
 /** @type {(string|number)} */
Props.prototype.width;

/**
 * @return {void}
 */
Props.prototype.onStateChange = function() {};
/**
 * @constructor
 * @struct
 */
function ReactBurgerMenu() {}
/**
 * @constructor
 * @struct
 */
function slide() {}
/**
 * @constructor
 * @struct
 */
function stack() {}
/**
 * @constructor
 * @struct
 */
function elastic() {}
/**
 * @constructor
 * @struct
 */
function bubble() {}
/**
 * @constructor
 * @struct
 */
function push() {}
/**
 * @constructor
 * @struct
 */
function pushRotate() {}
/**
 * @constructor
 * @struct
 */
function scaleDown() {}
/**
 * @constructor
 * @struct
 */
function scaleRotate() {}
/**
 * @constructor
 * @struct
 */
function fallDown() {}
