/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/storybook__react/index.d.ts:

/* TODO: ImportDeclaration in  */

/** @typedef {(!React.StatelessComponent<?>|!React.ComponentClass<?>|!JSX.Element)} */
var Renderable;

/** @typedef {?} */
var RenderFunction;

/** @typedef {?} */
var StoryDecorator;
/**
 * @record
 * @struct
 */
function Story() {}
 /** @type {string} */
Story.prototype.kind;

/**
 * @param {string} storyName
 * @param {?} callback
 * @return {?}
 */
Story.prototype.add = function(storyName, callback) {};

/**
 * @param {?} decorator
 * @return {?}
 */
Story.prototype.addDecorator = function(decorator) {};

/**
 * @param {?} decorator
 * @return {void}
 */
function addDecorator(decorator) {}

/**
 * @param {?} fn
 * @param {?} module
 * @return {void}
 */
function configure(fn, module) {}

/**
 * @param {!Object} addon
 * @return {void}
 */
function setAddon(addon) {}

/**
 * @template T
 * @param {string} name
 * @param {!NodeModule} module
 * @return {?}
 */
function storiesOf(name, module) {}
/**
 * @record
 * @struct
 */
function StoryObject() {}
 /** @type {string} */
StoryObject.prototype.name;
 /** @type {?} */
StoryObject.prototype.render;
/**
 * @record
 * @struct
 */
function StoryBucket() {}
 /** @type {string} */
StoryBucket.prototype.kind;
 /** @type {!Array<?>} */
StoryBucket.prototype.stories;

/**
 * @return {!Array<?>}
 */
function getStorybook() {}
