/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/svg4everybody/index.d.ts:

/* TODO: NamespaceExportDeclaration in  */

/* TODO: ExportAssignment in  */

/**
 * @param {!svg4everybody.Svg4everybodyOpts=} options
 * @return {void}
 */
function svg4everybody(options) {}
/**
 * @record
 * @struct
 */
svg4everybody.Svg4everybodyOpts = function() {};
 /** @type {boolean} */
svg4everybody.Svg4everybodyOpts.prototype.nosvg;
 /** @type {boolean} */
svg4everybody.Svg4everybodyOpts.prototype.polyfill;

/**
 * @param {string} src
 * @param {!SVGElement} svg
 * @param {!SVGUseElement} use
 * @return {string}
 */
svg4everybody.Svg4everybodyOpts.prototype.fallback = function(src, svg, use) {};

/**
 * @param {string} src
 * @param {!SVGElement} svg
 * @param {!SVGUseElement} use
 * @return {boolean}
 */
svg4everybody.Svg4everybodyOpts.prototype.validate = function(src, svg, use) {};
