/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/temp-write/index.d.ts:

/* TODO: ExportAssignment in  */

/**
 * @param {(string|?|!NodeJS.ReadableStream)} input
 * @param {string=} filepath
 * @return {!Promise<string>}
 */
function tempWrite(input, filepath) {}

/**
 * @param {(string|?)} input
 * @param {string=} filepath
 * @return {string}
 */
tempWrite.sync = function(input, filepath) {};
