/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/tweenjs/index.d.ts:

/**
 * @constructor
 * @struct
 */
createjs.CSSPlugin = function() {};
 /** @type {!Object} */
createjs.CSSPlugin.cssSuffixMap;

/**
 * @return {void}
 */
createjs.CSSPlugin.install = function() {};
/**
 * @constructor
 * @struct
 */
createjs.Ease = function() {};
 /** @type {function(number): number} */
createjs.Ease.backIn;
 /** @type {function(number): number} */
createjs.Ease.backInOut;
 /** @type {function(number): number} */
createjs.Ease.backOut;
 /** @type {function(number): number} */
createjs.Ease.bounceIn;
 /** @type {function(number): number} */
createjs.Ease.bounceInOut;
 /** @type {function(number): number} */
createjs.Ease.bounceOut;
 /** @type {function(number): number} */
createjs.Ease.circIn;
 /** @type {function(number): number} */
createjs.Ease.circInOut;
 /** @type {function(number): number} */
createjs.Ease.circOut;
 /** @type {function(number): number} */
createjs.Ease.cubicIn;
 /** @type {function(number): number} */
createjs.Ease.cubicInOut;
 /** @type {function(number): number} */
createjs.Ease.cubicOut;
 /** @type {function(number): number} */
createjs.Ease.elasticIn;
 /** @type {function(number): number} */
createjs.Ease.elasticInOut;
 /** @type {function(number): number} */
createjs.Ease.elasticOut;
 /** @type {function(number): number} */
createjs.Ease.linear;
 /** @type {function(number): number} */
createjs.Ease.none;
 /** @type {function(number): number} */
createjs.Ease.quadIn;
 /** @type {function(number): number} */
createjs.Ease.quadInOut;
 /** @type {function(number): number} */
createjs.Ease.quadOut;
 /** @type {function(number): number} */
createjs.Ease.quartIn;
 /** @type {function(number): number} */
createjs.Ease.quartInOut;
 /** @type {function(number): number} */
createjs.Ease.quartOut;
 /** @type {function(number): number} */
createjs.Ease.quintIn;
 /** @type {function(number): number} */
createjs.Ease.quintInOut;
 /** @type {function(number): number} */
createjs.Ease.quintOut;
 /** @type {function(number): number} */
createjs.Ease.sineIn;
 /** @type {function(number): number} */
createjs.Ease.sineInOut;
 /** @type {function(number): number} */
createjs.Ease.sineOut;

/**
 * @param {number} amount
 * @return {function(number): number}
 */
createjs.Ease.get = function(amount) {};

/**
 * @param {number} amount
 * @return {function(number): number}
 */
createjs.Ease.getBackIn = function(amount) {};

/**
 * @param {number} amount
 * @return {function(number): number}
 */
createjs.Ease.getBackInOut = function(amount) {};

/**
 * @param {number} amount
 * @return {function(number): number}
 */
createjs.Ease.getBackOut = function(amount) {};

/**
 * @param {number} amplitude
 * @param {number} period
 * @return {function(number): number}
 */
createjs.Ease.getElasticIn = function(amplitude, period) {};

/**
 * @param {number} amplitude
 * @param {number} period
 * @return {function(number): number}
 */
createjs.Ease.getElasticInOut = function(amplitude, period) {};

/**
 * @param {number} amplitude
 * @param {number} period
 * @return {function(number): number}
 */
createjs.Ease.getElasticOut = function(amplitude, period) {};

/**
 * @param {number} pow
 * @return {function(number): number}
 */
createjs.Ease.getPowIn = function(pow) {};

/**
 * @param {number} pow
 * @return {function(number): number}
 */
createjs.Ease.getPowInOut = function(pow) {};

/**
 * @param {number} pow
 * @return {function(number): number}
 */
createjs.Ease.getPowOut = function(pow) {};

/**
 * @constructor
 * @struct
 */
createjs.MotionGuidePlugin = function() {};

/**
 * @return {!Object}
 */
createjs.MotionGuidePlugin.install = function() {};

/**
 * @constructor
 * @struct
 * @param {!Array<!createjs.Tween>} tweens
 * @param {!Object} labels
 * @param {!Object} props
 */
createjs.Timeline = function(tweens, labels, props) {};
 /** @type {number} */
createjs.Timeline.prototype.duration;
 /** @type {boolean} */
createjs.Timeline.prototype.ignoreGlobalPause;
 /** @type {boolean} */
createjs.Timeline.prototype.loop;
 /** @type {!Object} */
createjs.Timeline.prototype.position;

/**
 * @param {string} label
 * @param {number} position
 * @return {void}
 */
createjs.Timeline.prototype.addLabel = function(label, position) {};

/**
 * @param {...!createjs.Tween} tween
 * @return {void}
 */
createjs.Timeline.prototype.addTween = function(tween) {};

/**
 * @return {string}
 */
createjs.Timeline.prototype.getCurrentLabel = function() {};

/**
 * @return {!Array<!Object>}
 */
createjs.Timeline.prototype.getLabels = function() {};

/**
 * @param {(string|number)} positionOrLabel
 * @return {void}
 */
createjs.Timeline.prototype.gotoAndPlay = function(positionOrLabel) {};

/**
 * @param {(string|number)} positionOrLabel
 * @return {void}
 */
createjs.Timeline.prototype.gotoAndStop = function(positionOrLabel) {};

/**
 * @param {...!createjs.Tween} tween
 * @return {void}
 */
createjs.Timeline.prototype.removeTween = function(tween) {};

/**
 * @param {(string|number)} positionOrLabel
 * @return {number}
 */
createjs.Timeline.prototype.resolve = function(positionOrLabel) {};

/**
 * @param {!Object} o
 * @return {void}
 */
createjs.Timeline.prototype.setLabels = function(o) {};

/**
 * @param {boolean} value
 * @return {void}
 */
createjs.Timeline.prototype.setPaused = function(value) {};

/**
 * @param {number} value
 * @param {number=} actionsMode
 * @return {boolean}
 */
createjs.Timeline.prototype.setPosition = function(value, actionsMode) {};

/**
 * @param {number} delta
 * @return {void}
 */
createjs.Timeline.prototype.tick = function(delta) {};

/**
 * @return {void}
 */
createjs.Timeline.prototype.updateDuration = function() {};

/**
 * @constructor
 * @struct
 * @param {!Object} target
 * @param {!Object=} props
 * @param {!Object=} pluginData
 */
createjs.Tween = function(target, props, pluginData) {};
 /** @type {number} */
createjs.Tween.prototype.duration;
 /** @type {!Object} */
createjs.Tween.IGNORE;
 /** @type {boolean} */
createjs.Tween.prototype.ignoreGlobalPause;
 /** @type {number} */
createjs.Tween.LOOP;
 /** @type {boolean} */
createjs.Tween.prototype.loop;
 /** @type {number} */
createjs.Tween.NONE;
 /** @type {!Function} */
createjs.Tween.prototype.onChange;
 /** @type {boolean} */
createjs.Tween.prototype.passive;
 /** @type {!Object} */
createjs.Tween.prototype.pluginData;
 /** @type {number} */
createjs.Tween.prototype.position;
 /** @type {number} */
createjs.Tween.REVERSE;
 /** @type {!Object} */
createjs.Tween.prototype.target;

/**
 * @param {function(!createjs.Tween): ?|function(!Array<?>): ?} callback
 * @param {!Array<?>=} params
 * @param {!Object=} scope
 * @return {!createjs.Tween}
 */
createjs.Tween.prototype.call = function(callback, params, scope) {};

/**
 * @param {!Object} target
 * @param {!Object=} props
 * @param {!Object=} pluginData
 * @param {boolean=} override
 * @return {!createjs.Tween}
 */
createjs.Tween.get = function(target, props, pluginData, override) {};

/**
 * @param {!Object=} target
 * @return {boolean}
 */
createjs.Tween.hasActiveTweens = function(target) {};

/**
 * @param {!Object} plugin
 * @param {!Array<?>} properties
 * @return {void}
 */
createjs.Tween.installPlugin = function(plugin, properties) {};

/**
 * @param {!createjs.Tween} tween
 * @return {!createjs.Tween}
 */
createjs.Tween.prototype.pause = function(tween) {};

/**
 * @param {!createjs.Tween} tween
 * @return {!createjs.Tween}
 */
createjs.Tween.prototype.play = function(tween) {};

/**
 * @return {void}
 */
createjs.Tween.removeAllTweens = function() {};

/**
 * @param {!Object} target
 * @return {void}
 */
createjs.Tween.removeTweens = function(target) {};

/**
 * @param {!Object} props
 * @param {!Object=} target
 * @return {!createjs.Tween}
 */
createjs.Tween.prototype.set = function(props, target) {};

/**
 * @param {boolean} value
 * @return {!createjs.Tween}
 */
createjs.Tween.prototype.setPaused = function(value) {};

/**
 * @param {number} value
 * @param {number} actionsMode
 * @return {boolean}
 */
createjs.Tween.prototype.setPosition = function(value, actionsMode) {};

/**
 * @param {number} delta
 * @param {boolean} paused
 * @return {void}
 */
createjs.Tween.tick = function(delta, paused) {};

/**
 * @param {number} delta
 * @return {void}
 */
createjs.Tween.prototype.tick = function(delta) {};

/**
 * @param {!Object} props
 * @param {number=} duration
 * @param {function(number): number=} ease
 * @return {!createjs.Tween}
 */
createjs.Tween.prototype.to = function(props, duration, ease) {};

/**
 * @param {number} duration
 * @param {boolean=} passive
 * @return {!createjs.Tween}
 */
createjs.Tween.prototype.wait = function(duration, passive) {};
/**
 * @constructor
 * @struct
 */
createjs.TweenJS = function() {};
 /** @type {string} */
createjs.TweenJS.buildDate;
 /** @type {string} */
createjs.TweenJS.version;
