/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/tz-format/index.d.ts:

/**
 * @param {(number|!Date)=} date
 * @param {number=} offset
 * @return {string}
 */
function format(date, offset) {}

/* TODO: ExportAssignment in  */
