/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/ui-select/index.d.ts:

/* TODO: ImportDeclaration in  */
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "angular"
/** @const */
tsickle_declare_module.angular.ui = {};
/** @const */
tsickle_declare_module.angular.ui.select = {};
/**
 * @record
 * @struct
 */
tsickle_declare_module.angular.ui.select.ISelectConfig = function() {};
 /** @type {boolean} */
tsickle_declare_module.angular.ui.select.ISelectConfig.prototype.appendToBody;
 /** @type {boolean} */
tsickle_declare_module.angular.ui.select.ISelectConfig.prototype.resetSearchInput;
 /** @type {string} */
tsickle_declare_module.angular.ui.select.ISelectConfig.prototype.theme;
