/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from d/winston-dynamodb/index.d.ts:

/* TODO: ImportDeclaration in  */

/* TODO: ImportDeclaration in  */
/**
 * @record
 * @struct
 */
function DynamoDBTransportOptions() {}
 /** @type {boolean} */
DynamoDBTransportOptions.prototype.useEnvironment;
 /** @type {string} */
DynamoDBTransportOptions.prototype.accessKeyId;
 /** @type {string} */
DynamoDBTransportOptions.prototype.secretAccessKey;
 /** @type {string} */
DynamoDBTransportOptions.prototype.region;
 /** @type {string} */
DynamoDBTransportOptions.prototype.tableName;
 /** @type {string} */
DynamoDBTransportOptions.prototype.level;
 /** @type {boolean} */
DynamoDBTransportOptions.prototype.dynamoDoc;
/**
 * @extends {TransportInstance}
 * @record
 * @struct
 */
function DynamoDBTransportInstance() {}

/* TODO: ConstructSignature:  */

/**
 * @constructor
 * @struct
 * @param {?=} options
 */
function DynamoDB(options) {}
 /** @type {!Array<string>} */
DynamoDB.prototype.regions;
 /** @type {string} */
DynamoDB.prototype.name;
 /** @type {string} */
DynamoDB.prototype.level;
 /** @type {?} */
DynamoDB.prototype.db;
 /** @type {?} */
DynamoDB.prototype.AWS;
 /** @type {string} */
DynamoDB.prototype.region;
 /** @type {string} */
DynamoDB.prototype.tableName;
 /** @type {boolean} */
DynamoDB.prototype.dynamoDoc;

/**
 * @param {?} level
 * @param {?} msg
 * @param {?} meta
 * @param {?} callback
 * @return {?}
 */
DynamoDB.prototype.log = function(level, msg, meta, callback) {};
/** @const */
var tsickle_declare_module = {};
// Derived from: declare module "winston"
 /** @type {!DynamoDB} */
tsickle_declare_module.winston.Transports.prototype.DynamoDB;
